# -*- coding: utf-8 -*-
"""
Created on Sun Aug 12 13:56:19 2018

@author: s-siraki
"""


print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
print('HelloWorld!')
    
print('Good bye!')